ALTER TABLE winners ADD CONSTRAINT winners_users_fk FOREIGN KEY (users_id)
  REFERENCES users (id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE winners ADD CONSTRAINT winners_games_fk FOREIGN KEY (games_id)
  REFERENCES games (id) ON DELETE CASCADE ON UPDATE RESTRICT;